import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import luna from "@/public/luna-low-res.jpg";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex flex-row flex-wrap gap-4 py-4 shadow-lg lg:px-28 bg-mustard">
          <div>
            <Link href="/" className="flex-1">
              <Image
                src={luna}
                alt="logo"
                height={64}
                width={64}
                className="rounded-full transition-transform duration-700 ease-in-out hover:scale-125"
              />
            </Link>
          </div>
          <div className="flex flex-row flex-1 gap-16 justify-end items-center">
            <Link href="/aboutMe" className="text-md">
              O mnie
            </Link>
            <Link href="/posts"> Posty </Link>
            <Link href="/contact"> Kontakt </Link>
          </div>
        </nav>
        <main className="container mx-auto">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
